FROM python:3.8-slim as base

ADD requirements.txt /

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libxml2-dev   \
    libxslt-dev   \
    zlib1g-dev    \
    libpq-dev     \
    libffi-dev    \
    gcc           \
    libssl-dev && \
    pip3 install -r requirements.txt && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get purge -y \
    libxml2-dev   \
    libxslt-dev   \
    zlib1g-dev    \
    libffi-dev    \
    gcc           \
    libssl-dev && \
    apt-get -y autoremove

COPY . /usr/src/app
COPY create_user.py /usr/src/app
COPY ./rest_api /usr/src/app

WORKDIR /usr/src/app

ENTRYPOINT [ "/usr/src/app/entrypoints/daphne.sh" ]
